# Connexion à la base de données MySQL Sprint2
spring.datasource.url=jdbc:mariadb://localhost:3306/projet_note_sprint2
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Configuration JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Exécute le script SQL au démarrage
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:base.sql
spring.jpa.defer-datasource-initialization=true

# Changer le port pour Sprint2
server.port=8087
