# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/forage
spring.datasource.username=postgres
spring.datasource.password=nyaina
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration - Manual SQL mode
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

server.port=8095

# Seuil d'alerte en heures (approche calendrier)
seuil.alerte.duree.heures=72
