# Connexion à la base de données Forage (Script 3) - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/forage
spring.datasource.username=postgres
spring.datasource.password=nyaina

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Configuration JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Exécute le script SQL au démarrage
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:script3-forage.sql
spring.jpa.defer-datasource-initialization=true

# Changer le port pour Script 3
server.port=8088
